import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">GAddPatientAssigndoctor</Link>
        </li>
        <li>
          <Link to="/desktopfour">DesktopFour</Link>
        </li>
        <li>
          <Link to="/glogin">GLogin</Link>
        </li>
        <li>
          <Link to="/ghome">GHome</Link>
        </li>
        <li>
          <Link to="/gpatientstwo">GPatientsTwo</Link>
        </li>
        <li>
          <Link to="/gpatientsone">GPatientsOne</Link>
        </li>
        <li>
          <Link to="/gpatients">GPatients</Link>
        </li>
        <li>
          <Link to="/gpatientdetails">GPatientDetails</Link>
        </li>
        <li>
          <Link to="/gaddpatientbasicinfo">GAddPatientBasicInfo</Link>
        </li>
        <li>
          <Link to="/gaddpatientproblems">GAddPatientProblems</Link>
        </li>
        <li>
          <Link to="/gprofile">GProfile</Link>
        </li>
        <li>
          <Link to="/gdoctor">GDoctor</Link>
        </li>
        <li>
          <Link to="/gdoctorone">GDoctorOne</Link>
        </li>
        <li>
          <Link to="/gdoctordetails">GDoctorDetails</Link>
        </li>
        <li>
          <Link to="/gadddoctorbasicinfo">GAddDoctorBasicInfo</Link>
        </li>
        <li>
          <Link to="/gassignedpatients">GAssignedPatients</Link>
        </li>
        <li>
          <Link to="/gemr">GEMR</Link>
        </li>
        <li>
          <Link to="/gemrpreview">GEMRPreview</Link>
        </li>
        <li>
          <Link to="/gemrone">GEMROne</Link>
        </li>
        <li>
          <Link to="/gdiagnostic">GDiagnostic</Link>
        </li>
        <li>
          <Link to="/gdbloodtest">GDBloodTest</Link>
        </li>
        <li>
          <Link to="/gdbptest">GDBPTest</Link>
        </li>
        <li>
          <Link to="/gdultrasonicscan">GDUltrasonicScan</Link>
        </li>
        <li>
          <Link to="/gdxray">GDXRay</Link>
        </li>
        <li>
          <Link to="/gdrenalscan">GDRenalScan</Link>
        </li>
        <li>
          <Link to="/gdctscan">GDCTScan</Link>
        </li>
        <li>
          <Link to="/gaddpatientproblemsapp">GAddPatientProblemsApp</Link>
        </li>
        <li>
          <Link to="/gappointments">GAppointments</Link>
        </li>
        <li>
          <Link to="/gaddpatientbasicinfoapp">GAddPatientBasicInfoApp</Link>
        </li>
        <li>
          <Link to="/gbilldetails">GBillDetails</Link>
        </li>
        <li>
          <Link to="/gaddaccount">GAddAccount</Link>
        </li>
        <li>
          <Link to="/gaddpayment">GAddPayment</Link>
        </li>
        <li>
          <Link to="/gdebitreport">GDebitReport</Link>
        </li>
        <li>
          <Link to="/gpurchasebilling">GPurchaseBilling</Link>
        </li>
        <li>
          <Link to="/gaccountlist">GAccountList</Link>
        </li>
        <li>
          <Link to="/gpaymentlist">GPaymentList</Link>
        </li>
        <li>
          <Link to="/gcreditreport">GCreditReport</Link>
        </li>
        <li>
          <Link to="/gpatientbilling">GPatientBilling</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
